spring:
  application:
    name: authservice
  
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?allowPublicKeyRetrieval=true&useSSL=false
    username: "user"
    password: "user@123"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect  
  
server:
  port: 8081